/* ElementLab Peptides - product catalog
   93 SKUs across 9 categories. Prices are in USD (converted from the client's
   GBP price list at 1 GBP = 1.34 USD, rounded down to the nearest .99).
   Each dose carries its own product photo (`image`), so the picture always
   matches the size selected. `coverDose` is the size shown on cards and used
   as the default selection on the product page.
   Chemical data (CAS / formula / molecular weight) comes from the SDS sheets
   where one exists, otherwise from public chemical references. Fields that
   could not be verified are omitted rather than guessed. */

const CATEGORIES = [
  {"slug": "retatrutide", "name": "Retatrutide", "blurb": "Triple GIP/GLP-1/glucagon receptor agonist research material in vials, multi-use pens and pen kits.", "image": "assets/img/categories/retatrutide.jpg"},
  {"slug": "tirzepatide", "name": "Tirzepatide", "blurb": "Dual GIP/GLP-1 receptor agonist research material in a full range of vial sizes.", "image": "assets/img/categories/tirzepatide.jpg"},
  {"slug": "semaglutide", "name": "Semaglutide", "blurb": "GLP-1 receptor agonist research material for incretin-pathway studies.", "image": "assets/img/categories/semaglutide.jpg"},
  {"slug": "bpc-thymosin", "name": "BPC-157 & Thymosin", "blurb": "Tissue-repair and immune-signaling research peptides: BPC-157, Thymosin Beta 4 and Thymosin Alpha-1.", "image": "assets/img/categories/bpc-thymosin.jpg"},
  {"slug": "growth-hormone", "name": "CJC / Growth Hormone Peptides", "blurb": "GHRH analogs, growth hormone secretagogues and related fragments for GH-axis research.", "image": "assets/img/categories/growth-hormone.jpg"},
  {"slug": "research", "name": "Research Peptides", "blurb": "Neuro, cellular, dermal and melanocortin pathway research peptides.", "image": "assets/img/categories/research.jpg"},
  {"slug": "other", "name": "Other Products", "blurb": "Bioregulators, neuro-peptides, cofactors and specialty research compounds.", "image": "assets/img/categories/other.jpg"},
  {"slug": "mixing", "name": "Laboratory Supplies", "blurb": "Bacteriostatic water and acetic acid diluents for laboratory reconstitution.", "image": "assets/img/categories/mixing.jpg"},
  {"slug": "supplements", "name": "Supplements", "blurb": "Creatine and sports-nutrition supplements: powders, tablets, capsules, gummies and single-serve sachets from leading brands.", "image": "assets/img/categories/supplements.jpg"},
];

const PRODUCTS = [
  {"slug": "retatrutide", "name": "Retatrutide", "categories": ["retatrutide"], "appearance": "White Lyophilized Powder", "coverDose": "20mg", "doses": [{"label": "5mg", "priceCents": 4499, "image": "assets/img/products/vial-blue-cap-white-powder.jpg"}, {"label": "10mg", "priceCents": 6899, "image": "assets/img/products/vial-blue-cap-white-powder.jpg"}, {"label": "15mg", "priceCents": 9499, "image": "assets/img/products/vial-blue-cap-white-powder.jpg"}, {"label": "20mg", "priceCents": 11899, "image": "assets/img/products/vial-blue-cap-white-powder.jpg"}, {"label": "30mg", "priceCents": 15899, "image": "assets/img/products/vial-blue-cap-white-powder.jpg"}, {"label": "40mg", "priceCents": 19999, "image": "assets/img/products/vial-blue-cap-white-powder.jpg"}, {"label": "50mg", "priceCents": 23999, "image": "assets/img/products/vial-blue-cap-white-powder.jpg"}, {"label": "60mg", "priceCents": 27999, "image": "assets/img/products/vial-blue-cap-white-powder.jpg"}], "summary": "A triple GIP/GLP-1/glucagon receptor agonist studied in advanced metabolic research models.", "researchApplications": ["Triple incretin/glucagon receptor research", "Advanced metabolic pathway studies"], "image": "assets/img/products/vial-blue-cap-white-powder.jpg", "chem": {"cas": "2381089-83-2", "formula": "C221H342N46O68", "mw": "4731.33 g/mol"}},
  {"slug": "retatrutide-pen", "name": "Retatrutide Pen", "categories": ["retatrutide"], "appearance": "Multi-Use Pen", "coverDose": "40mg", "doses": [{"label": "40mg", "priceCents": 24999, "image": "assets/img/products/retatrutide-pen-40mg-box.jpg"}, {"label": "60mg", "priceCents": 32999, "image": "assets/img/products/retatrutide-pen-60mg-box.jpg"}], "summary": "Retatrutide supplied in a multi-use pen format for laboratory research. A triple GIP/GLP-1/glucagon receptor agonist studied in advanced metabolic research models.", "researchApplications": ["Triple incretin/glucagon receptor research", "Advanced metabolic pathway studies"], "image": "assets/img/products/retatrutide-pen-40mg-box.jpg", "chem": {"cas": "2381089-83-2", "formula": "C221H342N46O68", "mw": "4731.33 g/mol"}, "storage": "Follow the storage instructions supplied with the pen; protect from light"},
  {"slug": "retatrutide-pen-kit", "name": "Retatrutide Pen Kit", "categories": ["retatrutide"], "appearance": "Prefilled Pen Kit", "coverDose": "40mg", "doses": [{"label": "20mg", "priceCents": 19999, "image": "assets/img/products/retatrutide-pen-kit-20mg-box.jpg"}, {"label": "40mg", "priceCents": 24999, "image": "assets/img/products/retatrutide-pen-kit-40mg-box.jpg"}, {"label": "60mg", "priceCents": 32999, "image": "assets/img/products/retatrutide-pen-kit-60mg-box.jpg"}], "summary": "Retatrutide supplied as a prefilled-pen kit with pen needles for laboratory research; the strength per pen is shown on the pack. A triple GIP/GLP-1/glucagon receptor agonist studied in advanced metabolic research models.", "researchApplications": ["Triple incretin/glucagon receptor research", "Advanced metabolic pathway studies"], "image": "assets/img/products/retatrutide-pen-kit-40mg-box.jpg", "chem": {"cas": "2381089-83-2", "formula": "C221H342N46O68", "mw": "4731.33 g/mol"}, "storage": "Follow the storage instructions supplied with the kit; protect from light"},
  {"slug": "tirzepatide", "name": "Tirzepatide", "categories": ["tirzepatide"], "appearance": "White Lyophilized Powder", "coverDose": "20mg", "doses": [{"label": "5mg", "priceCents": 3499, "image": "assets/img/products/vial-blue-cap-white-powder.jpg"}, {"label": "10mg", "priceCents": 5499, "image": "assets/img/products/vial-blue-cap-white-powder.jpg"}, {"label": "15mg", "priceCents": 7199, "image": "assets/img/products/vial-blue-cap-white-powder.jpg"}, {"label": "20mg", "priceCents": 8899, "image": "assets/img/products/vial-blue-cap-white-powder.jpg"}, {"label": "30mg", "priceCents": 11899, "image": "assets/img/products/vial-blue-cap-white-powder.jpg"}, {"label": "40mg", "priceCents": 14499, "image": "assets/img/products/vial-blue-cap-white-powder.jpg"}, {"label": "50mg", "priceCents": 16899, "image": "assets/img/products/vial-blue-cap-white-powder.jpg"}, {"label": "60mg", "priceCents": 19499, "image": "assets/img/products/vial-blue-cap-white-powder.jpg"}], "summary": "A dual GIP/GLP-1 receptor agonist studied extensively in metabolic and weight-regulation research.", "researchApplications": ["Dual incretin receptor pathway research", "Metabolic and weight-regulation studies"], "image": "assets/img/products/vial-blue-cap-white-powder.jpg", "chem": {"cas": "2023788-19-2", "formula": "C225H348N48O68", "mw": "4813.45 g/mol"}},
  {"slug": "semaglutide", "name": "Semaglutide", "categories": ["semaglutide"], "appearance": "White Lyophilized Powder", "coverDose": "10mg", "doses": [{"label": "5mg", "priceCents": 3899, "image": "assets/img/products/vial-blue-cap-white-powder.jpg"}, {"label": "10mg", "priceCents": 6499, "image": "assets/img/products/vial-blue-cap-white-powder.jpg"}], "summary": "A GLP-1 receptor agonist widely studied in metabolic, appetite, and glucose-regulation research.", "researchApplications": ["GLP-1 receptor pathway research", "Appetite and glucose-regulation studies"], "image": "assets/img/products/vial-blue-cap-white-powder.jpg", "chem": {"cas": "910463-68-2", "formula": "C187H291N45O59", "mw": "4113.58 g/mol"}},
  {"slug": "bpc-157", "name": "BPC-157", "categories": ["bpc-thymosin"], "appearance": "White Lyophilized Powder", "coverDose": "10mg", "doses": [{"label": "5mg", "priceCents": 1699, "image": "assets/img/products/vial-yellow-cap-white-powder.jpg"}, {"label": "10mg", "priceCents": 2999, "image": "assets/img/products/vial-yellow-cap-white-powder.jpg"}], "summary": "A synthetic peptide fragment studied in preclinical models for gastrointestinal and connective-tissue research applications.", "researchApplications": ["Gastrointestinal lining repair models", "Tendon and connective-tissue research", "Angiogenesis and wound-healing pathway studies"], "image": "assets/img/products/vial-yellow-cap-white-powder.jpg", "chem": {"cas": "137525-51-0 (free base); 1628202-19-6 (acetate)", "formula": "C62H98N16O22", "mw": "1419.55 g/mol"}},
  {"slug": "tb-500", "name": "Thymosin Beta 4 (TB-500)", "categories": ["bpc-thymosin"], "appearance": "White Lyophilized Powder", "coverDose": "5mg", "doses": [{"label": "2mg", "priceCents": 1699, "image": "assets/img/products/vial-yellow-cap-white-powder.jpg"}, {"label": "5mg", "priceCents": 3299, "image": "assets/img/products/vial-yellow-cap-white-powder.jpg"}, {"label": "10mg", "priceCents": 5499, "image": "assets/img/products/vial-yellow-cap-white-powder.jpg"}], "summary": "A synthetic version of Thymosin Beta-4, studied for its role in actin regulation and cell-migration research.", "researchApplications": ["Actin regulation and cell-migration studies", "Tissue-repair pathway research", "Often studied alongside BPC-157"], "image": "assets/img/products/vial-yellow-cap-white-powder.jpg", "chem": {"cas": "77591-33-4", "formula": "C212H350N56O78S", "mw": "4963.44 g/mol"}},
  {"slug": "thymosin-alpha-1", "name": "Thymosin Alpha-1", "categories": ["bpc-thymosin"], "appearance": "White Lyophilized Powder", "coverDose": "5mg", "doses": [{"label": "5mg", "priceCents": 4499, "image": "assets/img/products/vial-yellow-cap-white-powder.jpg"}], "summary": "A 28-amino-acid thymic peptide studied for its role in immune-cell signaling and T-cell maturation in laboratory models.", "researchApplications": ["Immune-cell signaling and T-cell maturation studies", "Cytokine and dendritic-cell pathway research"], "image": "assets/img/products/vial-yellow-cap-white-powder.jpg", "chem": {"cas": "62304-98-7", "formula": "C129H215N33O55", "mw": "3108.28 g/mol"}},
  {"slug": "cjc-1295-no-dac", "name": "CJC-1295 MOD GRF (no DAC)", "categories": ["growth-hormone"], "appearance": "White Lyophilized Powder", "coverDose": "5mg", "doses": [{"label": "2mg", "priceCents": 1299, "image": "assets/img/products/vial-yellow-cap-white-powder.jpg"}, {"label": "5mg", "priceCents": 2599, "image": "assets/img/products/vial-yellow-cap-white-powder.jpg"}], "summary": "A GHRH analog (Mod GRF 1-29) studied for its short-acting growth-hormone secretagogue properties in research models.", "researchApplications": ["Growth-hormone secretagogue research", "Short-acting GHRH pathway studies"], "image": "assets/img/products/vial-yellow-cap-white-powder.jpg", "chem": {"cas": "863288-34-0", "formula": "C152H252N44O42", "mw": "3367.9 g/mol"}},
  {"slug": "cjc-1295-dac", "name": "CJC-1295 With DAC", "categories": ["growth-hormone"], "appearance": "White Lyophilized Powder", "coverDose": "5mg", "doses": [{"label": "2mg", "priceCents": 2199, "image": "assets/img/products/vial-yellow-cap-white-powder.jpg"}, {"label": "5mg", "priceCents": 3999, "image": "assets/img/products/vial-yellow-cap-white-powder.jpg"}], "summary": "A long-acting GHRH analog studied for sustained growth-hormone secretagogue research applications.", "researchApplications": ["Sustained-release GHRH pathway research", "Long-acting secretagogue studies"], "image": "assets/img/products/vial-yellow-cap-white-powder.jpg", "chem": {"cas": "863288-34-0", "formula": "C165H269N47O46", "mw": "3647.16 g/mol"}},
  {"slug": "ipamorelin", "name": "Ipamorelin", "categories": ["growth-hormone"], "appearance": "White Lyophilized Powder", "coverDose": "5mg", "doses": [{"label": "2mg", "priceCents": 999, "image": "assets/img/products/vial-yellow-cap-white-powder.jpg"}, {"label": "5mg", "priceCents": 2099, "image": "assets/img/products/vial-yellow-cap-white-powder.jpg"}], "summary": "A selective pentapeptide growth hormone secretagogue studied for its action at the ghrelin (GHS-R1a) receptor in research models.", "researchApplications": ["Ghrelin/GHS-R1a receptor pathway research", "Growth-hormone release studies"], "image": "assets/img/products/vial-yellow-cap-white-powder.jpg", "chem": {"cas": "170851-70-4", "formula": "C38H49N9O5", "mw": "711.85 g/mol"}},
  {"slug": "ghrp-2", "name": "GHRP-2", "categories": ["growth-hormone"], "appearance": "White Lyophilized Powder", "coverDose": "5mg", "doses": [{"label": "5mg", "priceCents": 999, "image": "assets/img/products/vial-yellow-cap-white-powder.jpg"}, {"label": "10mg", "priceCents": 1899, "image": "assets/img/products/vial-yellow-cap-white-powder.jpg"}], "summary": "A synthetic hexapeptide growth hormone secretagogue studied for its activity at the ghrelin receptor.", "researchApplications": ["GHS-R1a receptor binding research", "Growth-hormone release pathway studies"], "image": "assets/img/products/vial-yellow-cap-white-powder.jpg", "chem": {"cas": "158861-67-7", "formula": "C45H55N9O6", "mw": "817.99 g/mol"}},
  {"slug": "ghrp-6", "name": "GHRP-6", "categories": ["growth-hormone"], "appearance": "White Lyophilized Powder", "coverDose": "5mg", "doses": [{"label": "5mg", "priceCents": 999, "image": "assets/img/products/vial-yellow-cap-white-powder.jpg"}, {"label": "10mg", "priceCents": 1899, "image": "assets/img/products/vial-yellow-cap-white-powder.jpg"}], "summary": "A first-generation synthetic hexapeptide growth hormone secretagogue studied at the ghrelin receptor.", "researchApplications": ["Ghrelin receptor pathway research", "Growth-hormone release and appetite-signaling studies"], "image": "assets/img/products/vial-yellow-cap-white-powder.jpg", "chem": {"cas": "87616-84-0", "formula": "C46H56N12O6", "mw": "873.01 g/mol"}},
  {"slug": "hexarelin", "name": "Hexarelin", "categories": ["growth-hormone"], "appearance": "White Lyophilized Powder", "coverDose": "2mg", "doses": [{"label": "2mg", "priceCents": 1399, "image": "assets/img/products/vial-yellow-cap-white-powder.jpg"}], "summary": "A synthetic hexapeptide growth hormone secretagogue studied for ghrelin-receptor activity and cardiac-tissue effects in preclinical models.", "researchApplications": ["Ghrelin/GHS receptor research", "Cardiac-tissue signaling studies in animal models"], "image": "assets/img/products/vial-yellow-cap-white-powder.jpg", "chem": {"cas": "140703-51-1", "formula": "C47H58N12O6", "mw": "887.04 g/mol"}},
  {"slug": "tesamorelin", "name": "Tesamorelin", "categories": ["growth-hormone"], "appearance": "White Lyophilized Powder", "coverDose": "2mg", "doses": [{"label": "2mg", "priceCents": 2899, "image": "assets/img/products/vial-yellow-cap-white-powder.jpg"}], "summary": "A 44-amino-acid synthetic analog of growth hormone-releasing hormone (GHRH), studied in growth-hormone axis and lipid-metabolism research.", "researchApplications": ["GHRH receptor pathway research", "Growth-hormone axis and lipid-metabolism studies"], "image": "assets/img/products/vial-yellow-cap-white-powder.jpg", "chem": {"cas": "218949-48-5", "formula": "C221H366N72O67S", "mw": "5135.86 g/mol"}},
  {"slug": "hgh-fragment-176-191", "name": "HGH Fragment 176-191", "categories": ["growth-hormone"], "appearance": "White Lyophilized Powder", "coverDose": "5mg", "doses": [{"label": "2mg", "priceCents": 1399, "image": "assets/img/products/vial-yellow-cap-white-powder.jpg"}, {"label": "5mg", "priceCents": 2899, "image": "assets/img/products/vial-yellow-cap-white-powder.jpg"}], "summary": "A C-terminal fragment of human growth hormone (residues 176-191) studied in lipid-metabolism research models.", "researchApplications": ["Lipid metabolism research", "Fat-cell signaling studies"], "image": "assets/img/products/vial-yellow-cap-white-powder.jpg", "chem": {"cas": "66004-57-7", "formula": "C78H123N23O22S2", "mw": "1799.10 g/mol"}},
  {"slug": "igf-lr3", "name": "IGF-1 LR3", "categories": ["growth-hormone"], "appearance": "White Lyophilized Powder", "coverDose": "1mg", "doses": [{"label": "1mg", "priceCents": 5899, "image": "assets/img/products/vial-yellow-cap-white-powder.jpg"}], "summary": "A long-acting analog of insulin-like growth factor 1, studied in muscle-growth and cell-proliferation research models.", "researchApplications": ["Muscle-growth pathway research", "Cell-proliferation studies"], "image": "assets/img/products/vial-yellow-cap-white-powder.jpg", "thinData": true, "chem": {"cas": "946870-92-4", "formula": "C400H625N111O115S9", "mw": "9117.6 g/mol"}},
  {"slug": "ghk-cu", "name": "GHK-Cu (Copper Peptide)", "categories": ["research"], "appearance": "Blue Lyophilized Powder", "coverDose": "50mg", "doses": [{"label": "50mg", "priceCents": 2699, "image": "assets/img/products/vial-yellow-cap-blue-powder.jpg"}], "summary": "A naturally occurring copper peptide studied extensively in dermal-repair and collagen-signaling research.", "researchApplications": ["Dermal-repair and collagen-signaling research", "Copper-peptide skin studies"], "image": "assets/img/products/vial-yellow-cap-blue-powder.jpg", "chem": {"cas": "49557-75-7", "formula": "C14H24CuN6O4", "mw": "403.9 g/mol"}},
  {"slug": "epitalon", "name": "Epitalon", "categories": ["research"], "appearance": "White Lyophilized Powder", "coverDose": "10mg", "doses": [{"label": "10mg", "priceCents": 1899, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "A synthetic tetrapeptide (Ala-Glu-Asp-Gly) modeled on the pineal peptide epithalamin, studied in cellular-aging and telomerase research.", "researchApplications": ["Telomerase and cellular-aging pathway research", "Pineal-peptide and circadian-signaling studies"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "chem": {"cas": "307297-39-8", "formula": "C14H22N4O9", "mw": "390.35 g/mol"}},
  {"slug": "dsip", "name": "DSIP", "categories": ["research"], "appearance": "White Lyophilized Powder", "coverDose": "5mg", "doses": [{"label": "5mg", "priceCents": 1399, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "Delta sleep-inducing peptide, a nonapeptide studied in sleep-regulation and stress-response research models.", "researchApplications": ["Sleep-regulation pathway research", "Stress-response and neuroendocrine studies"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "chem": {"cas": "62568-57-4", "formula": "C35H48N10O15", "mw": "848.81 g/mol"}},
  {"slug": "pt-141", "name": "PT-141 (Bremelanotide)", "categories": ["research"], "appearance": "White Lyophilized Powder", "coverDose": "10mg", "doses": [{"label": "10mg", "priceCents": 2099, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "Bremelanotide, a cyclic heptapeptide melanocortin receptor agonist studied for MC3R/MC4R signaling in research models.", "researchApplications": ["Melanocortin receptor (MC3R/MC4R) signaling research", "Central-pathway studies in animal models"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "chem": {"cas": "189691-06-3", "formula": "C50H68N14O10", "mw": "1025.18 g/mol"}},
  {"slug": "aod-9604", "name": "AOD 9604", "categories": ["research"], "appearance": "White Lyophilized Powder", "coverDose": "5mg", "doses": [{"label": "2mg", "priceCents": 2799, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}, {"label": "5mg", "priceCents": 5499, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "A modified fragment of human growth hormone studied in lipid-metabolism research models.", "researchApplications": ["Lipid metabolism research", "Fat-cell signaling studies"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "chem": {"cas": "221231-10-3", "formula": "C78H123N23O23S2", "mw": "1815.1 g/mol"}},
  {"slug": "mots-c", "name": "MOTS-C", "categories": ["research"], "appearance": "White Lyophilized Powder", "coverDose": "10mg", "doses": [{"label": "10mg", "priceCents": 2999, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "A mitochondrial-derived peptide studied for its role in metabolic homeostasis and exercise-response research.", "researchApplications": ["Mitochondrial-derived peptide research", "Exercise-response and metabolic homeostasis studies"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "chem": {"cas": "1627580-64-6", "formula": "C101H152N28O22S2", "mw": "2174.6 g/mol"}},
  {"slug": "kpv", "name": "KPV", "categories": ["research"], "appearance": "White Lyophilized Powder", "coverDose": "10mg", "doses": [{"label": "5mg", "priceCents": 2999, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}, {"label": "10mg", "priceCents": 4899, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "A tripeptide fragment of alpha-MSH studied for its anti-inflammatory signaling properties.", "researchApplications": ["Anti-inflammatory signaling research", "Alpha-MSH fragment studies"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "chem": {"cas": "67727-97-3", "formula": "C19H33N5O4", "mw": "395.50 g/mol"}},
  {"slug": "ll-37", "name": "LL-37", "categories": ["research"], "appearance": "White Lyophilized Powder", "coverDose": "5mg", "doses": [{"label": "5mg", "priceCents": 6899, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "The human cathelicidin antimicrobial peptide, studied for its antimicrobial and immune-modulating activity in vitro.", "researchApplications": ["Antimicrobial peptide mechanism studies", "Innate-immune signaling research", "Wound-healing models"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "chem": {"cas": "154947-66-7", "formula": "C205H340N60O53", "mw": "4493.33 g/mol"}},
  {"slug": "melanotan-2", "name": "Melanotan 2", "categories": ["research"], "appearance": "White Lyophilized Powder", "coverDose": "10mg", "doses": [{"label": "10mg", "priceCents": 2899, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "A synthetic cyclic analog of alpha-MSH studied for melanocortin-receptor activity and pigmentation pathways in research models.", "researchApplications": ["Melanocortin receptor signaling research", "Pigmentation pathway studies"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "chem": {"cas": "121062-08-6", "formula": "C50H69N15O9", "mw": "1024.18 g/mol"}},
  {"slug": "selank", "name": "Selank", "categories": ["research"], "appearance": "White Lyophilized Powder", "coverDose": "5mg", "doses": [{"label": "5mg", "priceCents": 3199, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "A synthetic heptapeptide analog of tuftsin studied for neuromodulatory and anxiolytic-like signaling in preclinical models.", "researchApplications": ["Neuromodulatory signaling research", "Anxiety-related behavior in animal models", "Immune-modulation studies"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "chem": {"cas": "129954-34-3", "formula": "C33H57N11O9", "mw": "751.89 g/mol"}},
  {"slug": "semax", "name": "Semax", "categories": ["research"], "appearance": "White Lyophilized Powder", "coverDose": "5mg", "doses": [{"label": "5mg", "priceCents": 3199, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "A synthetic heptapeptide analog of ACTH(4-10) studied for neurotrophic signaling in preclinical models.", "researchApplications": ["BDNF/neurotrophin signaling research", "Neuroprotection models"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "chem": {"cas": "80714-61-0", "formula": "C37H51N9O10S", "mw": "813.92 g/mol"}},
  {"slug": "kisspeptin-10", "name": "Kisspeptin-10", "categories": ["research"], "appearance": "White Lyophilized Powder", "coverDose": "5mg", "doses": [{"label": "5mg", "priceCents": 3899, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "A decapeptide fragment of kisspeptin (metastin) studied for KISS1R signaling and GnRH-axis regulation in research models.", "researchApplications": ["KISS1R receptor signaling research", "GnRH-axis regulation studies"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "chem": {"cas": "374675-21-5", "formula": "C63H83N17O14", "mw": "1302.45 g/mol"}},
  {"slug": "ace-031", "name": "ACE-031", "categories": ["other"], "appearance": "White Lyophilized Powder", "coverDose": "1mg", "doses": [{"label": "1mg", "priceCents": 7899, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "A soluble activin receptor type IIB (ActRIIB) construct studied as a ligand trap for myostatin and related TGF-beta family members.", "researchApplications": ["Myostatin/activin signaling research", "Skeletal-muscle model studies"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "thinData": true},
  {"slug": "adamax", "name": "ADAMAX", "categories": ["other"], "appearance": "White Lyophilized Powder", "coverDose": "5mg", "doses": [{"label": "5mg", "priceCents": 4899, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "An N-acetylated, adamantane-modified analog of Semax studied in comparative neuropeptide research.", "researchApplications": ["Semax-analog structure-activity comparisons", "Neurotrophic signaling studies"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "thinData": true, "chem": {"cas": "Not assigned", "formula": "C50H69N11O11S", "mw": "1032.23 g/mol"}},
  {"slug": "ara-290", "name": "ARA-290 (Cibinetide)", "categories": ["other"], "appearance": "White Lyophilized Powder", "coverDose": "16mg", "doses": [{"label": "16mg", "priceCents": 7499, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "An 11-amino-acid peptide derived from erythropoietin, designed to engage the innate repair receptor without erythropoietic activity.", "researchApplications": ["Innate repair receptor research", "Neuropathy and tissue-protection models"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "chem": {"cas": "1208243-50-8", "formula": "C51H84N16O21", "mw": "1257.31 g/mol"}},
  {"slug": "bronchogen", "name": "Bronchogen", "categories": ["other"], "appearance": "White Lyophilized Powder", "coverDose": "20mg", "doses": [{"label": "20mg", "priceCents": 3899, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "A synthetic tetrapeptide (Ala-Glu-Asp-Leu) bioregulator studied in bronchial-tissue and respiratory-epithelium research models.", "researchApplications": ["Bronchopulmonary bioregulator research", "Respiratory-tissue studies"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "thinData": true, "chem": {"cas": "Not assigned", "formula": "C18H30N4O9", "mw": "446.46 g/mol"}},
  {"slug": "cartalax", "name": "Cartalax", "categories": ["other"], "appearance": "White Lyophilized Powder", "coverDose": "20mg", "doses": [{"label": "20mg", "priceCents": 4899, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "A cartilage-tissue peptide bioregulator studied in connective-tissue aging research.", "researchApplications": ["Cartilage-tissue bioregulator research", "Connective-tissue aging studies"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "thinData": true, "chem": {"cas": "Not assigned", "formula": "C12H19N3O8", "mw": "333.29 g/mol"}},
  {"slug": "colivelin", "name": "Colivelin", "categories": ["other"], "appearance": "White Lyophilized Powder", "coverDose": "10mg", "doses": [{"label": "10mg", "priceCents": 6999, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "A humanin-derived neuroprotective peptide fused to ADNF, studied as a STAT3 activator in neuronal-survival models.", "researchApplications": ["STAT3 signaling research", "Neuroprotection and neuronal-survival models"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "chem": {"cas": "867021-83-8", "formula": "C119H206N32O35", "mw": "2645.10 g/mol"}},
  {"slug": "cortagen", "name": "Cortagen", "categories": ["other"], "appearance": "White Lyophilized Powder", "coverDose": "20mg", "doses": [{"label": "20mg", "priceCents": 4899, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "A synthetic tetrapeptide (Ala-Glu-Asp-Pro) bioregulator derived from cortex-peptide analysis, studied in neural-tissue and gene-expression research.", "researchApplications": ["Gene-expression and chromatin studies", "Peripheral-nerve tissue models"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "thinData": true, "chem": {"cas": "Not assigned", "formula": "C17H26N4O9", "mw": "430.41 g/mol"}},
  {"slug": "crystagen", "name": "Crystagen", "categories": ["other"], "appearance": "White Lyophilized Powder", "coverDose": "20mg", "doses": [{"label": "20mg", "priceCents": 5899, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "A short-peptide bioregulator studied in immune-system aging research models.", "researchApplications": ["Immune-tissue bioregulator research"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "thinData": true},
  {"slug": "dermorphin", "name": "Dermorphin", "categories": ["other"], "appearance": "White Lyophilized Powder", "coverDose": "2mg", "doses": [{"label": "2mg", "priceCents": 2899, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "A heptapeptide originally isolated from amphibian skin and a potent mu-opioid receptor agonist, studied in receptor-pharmacology research.", "researchApplications": ["Mu-opioid receptor pharmacology research", "Peptide-receptor binding studies"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "chem": {"cas": "77614-16-5", "formula": "C40H50N8O10", "mw": "802.87 g/mol"}},
  {"slug": "dihexa", "name": "Dihexa", "categories": ["other"], "appearance": "White Lyophilized Powder", "coverDose": "10mg", "doses": [{"label": "10mg", "priceCents": 5899, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "An angiotensin IV-derived oligopeptide that potentiates HGF/c-Met signaling, studied in synaptogenesis and cognition models.", "researchApplications": ["HGF/c-Met signaling research", "Synaptogenesis and cognition models"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "chem": {"cas": "1401708-83-5", "formula": "C27H44N4O5", "mw": "504.66 g/mol"}},
  {"slug": "dnsp-11", "name": "DNSP-11", "categories": ["other"], "appearance": "White Lyophilized Powder", "coverDose": "5mg", "doses": [{"label": "5mg", "priceCents": 7499, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "A GDNF-derived peptide fragment studied for its neurotrophic signaling properties.", "researchApplications": ["Neurotrophic signaling research", "GDNF pathway studies"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "thinData": true},
  {"slug": "follistatin", "name": "Follistatin (95% Purity)", "categories": ["other"], "appearance": "White Lyophilized Powder", "coverDose": "1mg", "doses": [{"label": "1mg", "priceCents": 7599, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "An activin-binding glycoprotein studied for its role in antagonizing myostatin and activin signaling.", "researchApplications": ["Myostatin/activin signaling research", "Skeletal-muscle model studies"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "thinData": true},
  {"slug": "nad-plus", "name": "NAD+", "categories": ["other"], "appearance": "White Lyophilized Powder", "coverDose": "500mg", "doses": [{"label": "250mg", "priceCents": 5499, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}, {"label": "500mg", "priceCents": 7499, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "Nicotinamide adenine dinucleotide, studied for its central role in cellular energy metabolism and longevity research.", "researchApplications": ["Cellular energy metabolism research", "Mitochondrial function and longevity studies"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "chem": {"cas": "53-84-9", "formula": "C21H27N7O14P2", "mw": "663.43 g/mol"}},
  {"slug": "thymalin", "name": "Thymalin", "categories": ["other"], "appearance": "White Lyophilized Powder", "coverDose": "2mg", "doses": [{"label": "2mg", "priceCents": 1099, "image": "assets/img/products/vial-red-cap-white-powder.jpg"}], "summary": "A thymic peptide bioregulator studied in immune-system aging research models.", "researchApplications": ["Thymic bioregulator research", "Immune-aging studies"], "image": "assets/img/products/vial-red-cap-white-powder.jpg", "thinData": true},
  {"slug": "bacteriostatic-water", "name": "Bacteriostatic Mixing Water", "categories": ["mixing"], "appearance": "Clear Sterile Liquid", "coverDose": "10ml", "doses": [{"label": "10ml", "priceCents": 499, "image": "assets/img/products/vial-blue-cap-liquid.jpg"}], "summary": "Sterile water containing a bacteriostatic preservative (typically benzyl alcohol), used to reconstitute lyophilized research peptides in the laboratory.", "researchApplications": ["Reconstitution of lyophilized research peptides", "Multi-draw laboratory dilution work"], "image": "assets/img/products/vial-blue-cap-liquid.jpg", "storage": "Store sealed at controlled room temperature"},
  {"slug": "acetic-acid", "name": "Acetic Acid 0.6% Solution", "categories": ["mixing"], "appearance": "Clear Liquid", "coverDose": "10ml", "doses": [{"label": "10ml", "priceCents": 599, "image": "assets/img/products/vial-blue-cap-liquid.jpg"}], "summary": "A 0.6% acetic acid solution used as a reconstitution diluent for peptides that dissolve best at low pH, such as IGF-1 LR3.", "researchApplications": ["Peptide reconstitution diluent", "Low-pH dissolution of hard-to-solubilize peptides"], "image": "assets/img/products/vial-blue-cap-liquid.jpg", "chem": {"cas": "64-19-7 (acetic acid)", "formula": "C2H4O2 (acetic acid)", "mw": "60.05 g/mol"}, "storage": "Store sealed at controlled room temperature"},
  {"slug": "weider-micronized-creatine-blue-raspberry-300g", "name": "Weider Micronized Creatine Monohydrate - Blue Raspberry", "categories": ["supplements"], "appearance": "Flavoured Powder (Blue Raspberry Bubblegum)", "coverDose": "300g", "doses": [{"label": "300g", "priceCents": 2499, "image": "assets/img/products/weider-micronized-creatine-blue-raspberry-300g.jpg"}], "summary": "Weider micronized creatine monohydrate powder in Blue Raspberry Bubblegum. 200 mesh ultrafine powder that mixes easily, with 60 servings per tub and AstraGin added.", "researchApplications": ["200 mesh ultrafine micronized creatine monohydrate", "60 servings per 300g tub", "Sugar free, fat free and stimulant free", "Blue Raspberry Bubblegum flavour"], "image": "assets/img/products/weider-micronized-creatine-blue-raspberry-300g.jpg", "storage": "Store in a cool, dry place away from direct sunlight. Keep tightly closed."},
  {"slug": "weider-micronized-creatine-unflavoured-310g", "name": "Weider Micronized Creatine Monohydrate - Unflavoured", "categories": ["supplements"], "appearance": "Unflavoured Powder", "coverDose": "310g", "doses": [{"label": "310g", "priceCents": 2399, "image": "assets/img/products/weider-micronized-creatine-unflavoured-310g.jpg"}], "summary": "Weider unflavoured micronized creatine monohydrate powder. 99% creatine monohydrate plus AstraGin, in a 200 mesh ultrafine grind for easy mixing.", "researchApplications": ["99% creatine monohydrate + AstraGin", "200 mesh ultrafine powder", "62 servings per 310g tub", "Sugar free, fat free and stimulant free"], "image": "assets/img/products/weider-micronized-creatine-unflavoured-310g.jpg", "storage": "Store in a cool, dry place away from direct sunlight. Keep tightly closed.", "chem": {"cas": "6020-87-7", "formula": "C4H9N3O2·H2O", "mw": "149.15 g/mol"}},
  {"slug": "weightworld-creatine-monohydrate-3000mg-270-tablets", "name": "WeightWorld Creatine Monohydrate 3000mg - 270 Tablets", "categories": ["supplements"], "appearance": "Tablets", "coverDose": "270 tablets", "doses": [{"label": "270 tablets", "priceCents": 2799, "image": "assets/img/products/weightworld-creatine-monohydrate-3000mg-270-tablets.jpg"}], "summary": "WeightWorld creatine monohydrate tablets providing 3000mg per daily portion (3 tablets). A powder-free way to take creatine; vegan, gluten free and GMO free. The pack carries a French label.", "researchApplications": ["3000mg creatine per portion (3 tablets daily)", "270 tablets, about a 3-month supply", "Vegan and gluten free", "French-language label"], "image": "assets/img/products/weightworld-creatine-monohydrate-3000mg-270-tablets.jpg", "storage": "Store in a cool, dry place away from direct sunlight. Keep tightly closed.", "chem": {"cas": "6020-87-7", "formula": "C4H9N3O2·H2O", "mw": "149.15 g/mol"}},
  {"slug": "weightworld-creatine-gummies-5k-lemon-90", "name": "WeightWorld Creatine Gummies 5K - Lemon", "categories": ["supplements"], "appearance": "Gummies (Natural Lemon Flavour)", "coverDose": "90 gummies", "doses": [{"label": "90 gummies", "priceCents": 2799, "image": "assets/img/products/weightworld-creatine-gummies-5k-lemon-90.jpg"}], "summary": "Sugar-free creatine gummies delivering 5000mg per serving in a natural lemon flavour. Vegan and easy to take with no mixing. The pack carries a French label.", "researchApplications": ["5000mg creatine per serving", "90 sugar-free vegan gummies", "Natural lemon flavour", "French-language label"], "image": "assets/img/products/weightworld-creatine-gummies-5k-lemon-90.jpg", "storage": "Store in a cool, dry place away from direct sunlight. Keep tightly closed."},
  {"slug": "gloryfeel-creatine-monohydrate-320-capsules", "name": "gloryfeel Creatine Monohydrate - 320 Capsules", "categories": ["supplements"], "appearance": "Capsules", "coverDose": "320 capsules", "doses": [{"label": "320 capsules", "priceCents": 2699, "image": "assets/img/products/gloryfeel-creatine-monohydrate-320-capsules.jpg"}], "summary": "gloryfeel creatine monohydrate capsules providing 3000mg per daily dose (3 capsules). A large 320-capsule tub for long-term daily use without powder.", "researchApplications": ["3000mg creatine per daily dose (3 capsules)", "320 capsules per tub", "Powder-free and easy to take"], "image": "assets/img/products/gloryfeel-creatine-monohydrate-320-capsules.jpg", "storage": "Store in a cool, dry place away from direct sunlight. Keep tightly closed.", "chem": {"cas": "6020-87-7", "formula": "C4H9N3O2·H2O", "mw": "149.15 g/mol"}},
  {"slug": "gloryfeel-creatine-powder-500g", "name": "gloryfeel Creatine Powder - Pure Monohydrate", "categories": ["supplements"], "appearance": "Unflavoured Powder", "coverDose": "500g", "doses": [{"label": "500g", "priceCents": 2999, "image": "assets/img/products/gloryfeel-creatine-powder-500g.jpg"}], "summary": "gloryfeel pure creatine monohydrate powder made with Creapure. Each serving gives 3409mg creatine monohydrate, of which 3000mg is creatine. Vegan.", "researchApplications": ["Made with Creapure creatine monohydrate", "3409mg monohydrate per serving (3000mg creatine)", "500g tub, vegan"], "image": "assets/img/products/gloryfeel-creatine-powder-500g.jpg", "storage": "Store in a cool, dry place away from direct sunlight. Keep tightly closed.", "chem": {"cas": "6020-87-7", "formula": "C4H9N3O2·H2O", "mw": "149.15 g/mol"}},
  {"slug": "nutri-plus-creatine-powder-500g", "name": "nutri+ Creatin Powder", "categories": ["supplements"], "appearance": "Unflavoured Powder", "coverDose": "500g", "doses": [{"label": "500g", "priceCents": 1999, "image": "assets/img/products/nutri-plus-creatine-powder-500g.jpg"}], "summary": "nutri+ plant-based unflavoured creatine powder in a resealable 500g pouch. Dissolves easily in water, juice or a shake.", "researchApplications": ["Vegan, plant-based", "Unflavoured, mixes into any drink", "500g resealable pouch"], "image": "assets/img/products/nutri-plus-creatine-powder-500g.jpg", "storage": "Store in a cool, dry place away from direct sunlight. Keep tightly closed.", "chem": {"cas": "6020-87-7", "formula": "C4H9N3O2·H2O", "mw": "149.15 g/mol"}},
  {"slug": "esn-ultrapure-creatine-300-capsules", "name": "ESN Ultrapure Creatine - 300 Vegan Capsules", "categories": ["supplements"], "appearance": "Vegan Capsules", "coverDose": "300 capsules", "doses": [{"label": "300 capsules", "priceCents": 4999, "image": "assets/img/products/esn-ultrapure-creatine-300-capsules.jpg"}], "summary": "ESN Ultrapure Creatine, a premium-grade pure creatine monohydrate in 300 vegan capsules (100 servings) from Elite Sports Nutrition.", "researchApplications": ["Premium grade pure creatine monohydrate", "300 vegan capsules, 100 servings", "Improves strength performance (label claim)"], "image": "assets/img/products/esn-ultrapure-creatine-300-capsules.jpg", "storage": "Store in a cool, dry place away from direct sunlight. Keep tightly closed.", "chem": {"cas": "6020-87-7", "formula": "C4H9N3O2·H2O", "mw": "149.15 g/mol"}},
  {"slug": "on-micronised-creatine-powder-unflavoured-187g", "name": "Optimum Nutrition Micronised Creatine Powder - 187g", "categories": ["supplements"], "appearance": "Unflavoured Powder", "coverDose": "187g", "doses": [{"label": "187g", "priceCents": 1999, "image": "assets/img/products/on-micronised-creatine-powder-unflavoured-187g.jpg"}], "summary": "Optimum Nutrition micronised creatine monohydrate powder in a 187g tub. 3g of creatine per serving, 55 servings; micronised for easy mixing.", "researchApplications": ["3g creatine per serving", "55 servings per tub", "Unflavoured, easy to stack with other supplements"], "image": "assets/img/products/on-micronised-creatine-powder-unflavoured-187g.jpg", "storage": "Store in a cool, dry place away from direct sunlight. Keep tightly closed.", "chem": {"cas": "6020-87-7", "formula": "C4H9N3O2·H2O", "mw": "149.15 g/mol"}},
  {"slug": "on-micronised-creatine-powder-unflavoured-317g", "name": "Optimum Nutrition Micronised Creatine Powder - 317g", "categories": ["supplements"], "appearance": "Unflavoured Powder", "coverDose": "317g", "doses": [{"label": "317g", "priceCents": 2999, "image": "assets/img/products/on-micronised-creatine-powder-unflavoured-317g.jpg"}], "summary": "Optimum Nutrition 100% pure micronised creatine monohydrate powder in a 317g tub. 3g of creatine per serving, 93 servings; add to water, juice or a shake.", "researchApplications": ["100% pure creatine monohydrate", "3g creatine per serving", "93 servings per tub"], "image": "assets/img/products/on-micronised-creatine-powder-unflavoured-317g.jpg", "storage": "Store in a cool, dry place away from direct sunlight. Keep tightly closed.", "chem": {"cas": "6020-87-7", "formula": "C4H9N3O2·H2O", "mw": "149.15 g/mol"}},
  {"slug": "on-micronised-creatine-powder-unflavoured-634g", "name": "Optimum Nutrition Micronised Creatine Powder - 634g", "categories": ["supplements"], "appearance": "Unflavoured Powder", "coverDose": "634g", "doses": [{"label": "634g", "priceCents": 4499, "image": "assets/img/products/on-micronised-creatine-powder-unflavoured-634g.jpg"}], "summary": "Optimum Nutrition micronised creatine monohydrate powder in the large 634g tub. 3g of creatine per serving and 186 servings, the best value size in the range.", "researchApplications": ["3g creatine per serving", "186 servings per tub", "Unflavoured, micronised for solubility"], "image": "assets/img/products/on-micronised-creatine-powder-unflavoured-634g.jpg", "storage": "Store in a cool, dry place away from direct sunlight. Keep tightly closed.", "chem": {"cas": "6020-87-7", "formula": "C4H9N3O2·H2O", "mw": "149.15 g/mol"}},
  {"slug": "on-micronised-creatine-powder-orange-247g", "name": "Optimum Nutrition Micronised Creatine Powder - Orange", "categories": ["supplements"], "appearance": "Flavoured Powder (Orange)", "coverDose": "247.5g", "doses": [{"label": "247.5g", "priceCents": 2499, "image": "assets/img/products/on-micronised-creatine-powder-orange-247g.jpg"}], "summary": "Optimum Nutrition micronised creatine powder in an orange flavour. 3g of creatine per serving and 55 servings in a 247.5g tub.", "researchApplications": ["3g creatine per serving", "55 servings per tub", "Orange flavour"], "image": "assets/img/products/on-micronised-creatine-powder-orange-247g.jpg", "storage": "Store in a cool, dry place away from direct sunlight. Keep tightly closed."},
  {"slug": "on-creatine-tablets-180", "name": "Optimum Nutrition Creatine Tablets", "categories": ["supplements"], "appearance": "Tablets", "coverDose": "180 tablets", "doses": [{"label": "180 tablets", "priceCents": 2499, "image": "assets/img/products/on-creatine-tablets-180.jpg"}], "summary": "Optimum Nutrition creatine monohydrate tablets, 3.0g of creatine monohydrate per serving. 180 tablets per tub, a no-mix option for daily use.", "researchApplications": ["3.0g creatine monohydrate per serving", "180 tablets per tub", "Powder-free and easy to take"], "image": "assets/img/products/on-creatine-tablets-180.jpg", "storage": "Store in a cool, dry place away from direct sunlight. Keep tightly closed.", "chem": {"cas": "6020-87-7", "formula": "C4H9N3O2·H2O", "mw": "149.15 g/mol"}},
  {"slug": "on-micronised-creatine-sachets-unflavoured-3-pack", "name": "Optimum Nutrition Micronised Creatine Sachets - Unflavoured (3 Boxes)", "categories": ["supplements"], "appearance": "Unflavoured Sachets (3 boxes of 10)", "coverDose": "3 boxes", "doses": [{"label": "3 boxes", "priceCents": 3499, "image": "assets/img/products/on-micronised-creatine-sachets-unflavoured-3-pack.jpg"}], "summary": "Three boxes of Optimum Nutrition micronised creatine sachets in one pack: 30 single-serve sachets in total (10 per 34g box), each with 3g of creatine. Ideal for travel and the gym bag.", "researchApplications": ["Sold as 3 boxes in one order", "30 single-serve sachets in total", "3g creatine per sachet, unflavoured"], "image": "assets/img/products/on-micronised-creatine-sachets-unflavoured-3-pack.jpg", "storage": "Store in a cool, dry place away from direct sunlight. Keep tightly closed."},
  {"slug": "on-micronised-creatine-sachets-fruit-punch-45g", "name": "Optimum Nutrition Micronised Creatine Sachets - Fruit Punch", "categories": ["supplements"], "appearance": "Flavoured Sachets (Fruit Punch)", "coverDose": "10 sachets", "doses": [{"label": "10 sachets", "priceCents": 1199, "image": "assets/img/products/on-micronised-creatine-sachets-fruit-punch-45g.jpg"}], "summary": "One box of 10 Optimum Nutrition micronised creatine sachets in Fruit Punch (45g). Each sachet gives 3g of creatine with no scooping or measuring.", "researchApplications": ["10 single-serve sachets (45g)", "3g creatine per sachet", "Fruit Punch flavour"], "image": "assets/img/products/on-micronised-creatine-sachets-fruit-punch-45g.jpg", "storage": "Store in a cool, dry place away from direct sunlight. Keep tightly closed."},
  {"slug": "on-platinum-creatine-plus-orange-astragin-350g", "name": "Optimum Nutrition Platinum Creatine Plus - Orange (AstraGin)", "categories": ["supplements"], "appearance": "Flavoured Powder (Orange)", "coverDose": "350g", "doses": [{"label": "350g", "priceCents": 4499, "image": "assets/img/products/on-platinum-creatine-plus-orange-astragin-350g.jpg"}], "summary": "Optimum Nutrition's advanced creatine formula with 3g of creatine, 500mg of AstraGin and 3mg of zinc per serving. Orange flavour, 50 servings. This is the AstraGin label version.", "researchApplications": ["3g creatine, 500mg AstraGin and 3mg zinc per serving", "Immunity and electrolyte support (label claim)", "50 servings per 350g tub, orange"], "image": "assets/img/products/on-platinum-creatine-plus-orange-astragin-350g.jpg", "storage": "Store in a cool, dry place away from direct sunlight. Keep tightly closed."},
  {"slug": "on-platinum-creatine-plus-orange-aquamin-350g", "name": "Optimum Nutrition Platinum Creatine Plus - Orange (Aquamin)", "categories": ["supplements"], "appearance": "Flavoured Powder (Orange)", "coverDose": "350g", "doses": [{"label": "350g", "priceCents": 4499, "image": "assets/img/products/on-platinum-creatine-plus-orange-aquamin-350g.jpg"}], "summary": "Optimum Nutrition's advanced creatine formula with 3g of creatine, 500mg of Aquamin and 3mg of zinc per serving. Orange flavour, 50 servings. This is the Aquamin label version.", "researchApplications": ["3g creatine, 500mg Aquamin and 3mg zinc per serving", "Immunity and electrolyte support (label claim)", "50 servings per 350g tub, orange"], "image": "assets/img/products/on-platinum-creatine-plus-orange-aquamin-350g.jpg", "storage": "Store in a cool, dry place away from direct sunlight. Keep tightly closed."},
  {"slug": "on-creatine-electrolyte-sachets-duo", "name": "Optimum Nutrition Creatine + Electrolyte Sachets Duo", "categories": ["supplements"], "appearance": "Sachets (2 boxes of 10)", "coverDose": "2 boxes", "doses": [{"label": "2 boxes", "priceCents": 2299, "image": "assets/img/products/on-creatine-electrolyte-sachets-duo.jpg"}], "summary": "Two-box set sold together: Micronised Creatine Sachets in Fruit Punch (10 sachets, 45g) and Electrolyte Sachets in Forest Berries (10 sachets, 60g). Electrolytes per sachet: 400mg sodium, 300mg potassium, 113mg magnesium.", "researchApplications": ["Sold as 2 boxes in one order", "Creatine: 3g per sachet, Fruit Punch", "Electrolytes: 400mg sodium, 300mg potassium, 113mg magnesium, Forest Berries"], "image": "assets/img/products/on-creatine-electrolyte-sachets-duo.jpg", "storage": "Store in a cool, dry place away from direct sunlight. Keep tightly closed."},
];

/* Combos: each has one or more `tiers` (mass options). Every tier stores
   its own separateCents/bundleCents so pricing is always exact for that
   specific combination of doses - never derived on the fly. */
const COMBOS = [];  // Bundle deals are discontinued; kept as an empty list so shared code keeps working.

function getCategory(slug) {
  return CATEGORIES.find((c) => c.slug === slug);
}
function getProduct(slug) {
  return PRODUCTS.find((p) => p.slug === slug);
}
function getCombo(slug) {
  return COMBOS.find((c) => c.slug === slug);
}
function combosForProduct(slug) {
  return COMBOS.filter((c) => c.tiers.some((t) => t.items.some((i) => i.slug === slug)));
}
function productsInCategory(catSlug) {
  return PRODUCTS.filter((p) => p.categories.includes(catSlug));
}
function getDose(product, label) {
  return product.doses.find((d) => d.label === label) || product.doses[0];
}
function getCoverDose(product) {
  return getDose(product, product.coverDose || product.doses[0].label);
}
function thumbOf(path) {
  return path ? path.replace("/products/", "/products/thumbs/") : "";
}
function getDoseImage(product, label) {
  const d = getDose(product, label);
  return (d && d.image) || product.image || "";
}
// Supplements (creatine etc.) use different wording than research peptides.
function isSupplement(p) {
  return !!(p && p.categories && p.categories.includes("supplements"));
}
function doseRange(p) {
  const labels = p.doses.map((d) => d.label);
  return labels.length > 3 ? `${labels[0]} - ${labels[labels.length - 1]}` : labels.join(" · ");
}
function doseCountBadgeHtml(p) {
  const n = p.doses ? p.doses.length : 0;
  if (n <= 1) return "";
  return `<span class="dose-count-chip">${n} sizes available</span>`;
}
function money(cents) {
  return `$${(cents / 100).toFixed(2)}`;
}
function formatPrice(p) {
  return money(getCoverDose(p).priceCents);
}

// ---------- Stock status ----------
// Prefers a real inStock flag (settable from /admin.html once Supabase is
// connected) over the thinData proxy used before that existed.
function getStockStatus(p) {
  if (typeof p.inStock === "boolean") return p.inStock ? "in" : "out";
  return p.thinData ? "low" : "in";
}
function stockBadgeHtml(p) {
  const status = getStockStatus(p);
  if (status === "out") return `<span class="stock-badge low-stock">Out of Stock</span>`;
  return status === "low"
    ? `<span class="stock-badge low-stock">Low Stock</span>`
    : `<span class="stock-badge in-stock">In Stock</span>`;
}

// ---------- Live catalog (admin panel support) ----------
// Fetches the live product/category/bundle/settings data saved through
// /admin.html (stored in Supabase, served via this Netlify Function) and
// overwrites the static arrays above IN PLACE, so every file that already
// references PRODUCTS/CATEGORIES/COMBOS by name keeps working unchanged.
// If the backend isn't connected yet (or the fetch fails for any reason),
// this quietly does nothing and the static fallback data above is what
// the site shows - this is expected, not an error state, until the site
// owner finishes wiring Supabase + Netlify env vars.
async function loadLiveCatalog() {
  try {
    const res = await fetch("/.netlify/functions/get-products");
    if (!res.ok) return;
    const data = await res.json();
    if (Array.isArray(data.categories) && data.categories.length) {
      CATEGORIES.length = 0;
      CATEGORIES.push(...data.categories);
    }
    if (Array.isArray(data.products) && data.products.length) {
      PRODUCTS.length = 0;
      PRODUCTS.push(...data.products);
    }
    if (false && Array.isArray(data.combos) && data.combos.length) {
      // Bundle deals are discontinued: live bundle rows are ignored.
      COMBOS.length = 0;
      COMBOS.push(...data.combos);
    }
    if (data.settings) {
      window.LIVE_SETTINGS = data.settings;
      if (typeof applyLiveSettings === "function") applyLiveSettings(data.settings);
    }
  } catch (err) {
    // Offline, backend not connected, or function not deployed - fine,
    // the static PRODUCTS/CATEGORIES/COMBOS arrays already loaded above
    // are used as-is.
  }
}
// Kick this off immediately; pages that render product/category/combo data
// await this shared promise before their first render (see shop.js,
// product.js and the inline scripts on index/combos/cart pages).
window.catalogReadyPromise = loadLiveCatalog();

// Escapes text before it's inserted into innerHTML via a template literal.
// Product/category/combo names, summaries, etc. all ultimately come from
// the admin panel (backed by Supabase once connected), so anything typed
// there - including an accidental stray HTML tag pasted from somewhere
// else - must never be interpreted as real markup on the live site. Use
// this around any admin-editable text field rendered into innerHTML.
function escapeHtml(str) {
  if (str == null) return "";
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
